# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
before_script:
- python -V
- apt update && apt install -y python3-dev
- python setup.py build
".tox":
  image: python:latest
  before_script:
  - pip install tox
  script:
  - tox
  variables:
    TOXENV: py
test:
  extends: ".tox"
  parallel:
    matrix:
    - IMAGE:
      - python:3.5
      - python:3.6
      - python:3.7
      - python:3.8
  image: "$IMAGE"
flake8:
  extends: ".tox"
  variables:
    TOXENV: flake8
black:
  extends: ".tox"
  variables:
    TOXENV: black
