# no stub files for those third-party libraries on typeshed
[[tool.mypy.overrides]]
module = [
  "betamax",
  "cachecontrol",
  "feedparser",
  "html2text",
  "pytest",
  "requests_file",
  "setuptools_scm",
  "unidecode",
  "xdg",
  "xdg.BaseDirectory",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov=feed2exec --doctest-modules"
# requires the catchlog pytest plugin:
# https://pypi.python.org/pypi/pytest-catchlog/
log_cli_level = "DEBUG"
